### ISSUE TITLE
Project Tweaks

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#103]
electricBoiler - up electricity from -200_000 to -4_100_000
```statsInfoAppliers: {
		electricityUseKWh: absolute(4_100_000),
		naturalGasMMBTU: absolute(-20_000), // since the flavor text says No. 2 oil... maybe add a new stat later
	},
	statsActualAppliers: {
		electricityUseKWh: absolute(4_100_000),
		naturalGasMMBTU: absolute(-20_000),```

solarPanelsCarPort - text, electricity, and cost change
```cost: 1570_000,
	hasSingleYearAppliers: true,
	relatedProjectSymbols: [Pages.solarPanelsCarPortMaintenance],
	statsInfoAppliers: {
		electricityUseKWh: absolute(-425_000),
	},
	statsActualAppliers: {
		electricityUseKWh: absolute(-425_000),
	},
	statsRecapAppliers: {
		financesAvailable: absolute(-30_000),
		moneySpent: absolute(30_000),
	},```
```
choiceInfoText: [
		`You decided to look into installing a small covered carport with a solar electricity generation system. Given the sizing of your parking lot and available room, you decide on a {0.25 MW system} and use 
		parking in the carport as an incentive to well-performing or energy-saving employees. You decide to pay for the carport outright and not via a power purchase agreement, so you {must fund the maintenance} of the panels from this budget.
	    You will receive {CREDITs} to your budget for the energy generated (and not purchased).`
```


change electricity (both statInfoAppliers and statActualAppliers) for the following projects
solarPanelsCarPortMaintenance: -425_000
solarRooftop: -4_250_000
midSolar: -1_440_000
largeWind-4_800_000

**Comment by rhernandez-intertech** [comment]
and cleaned up project titles

**Comment by koay9f** [comment]
Small carport solar cost should be 157_000
