### ISSUE TITLE
Quick fixes to projects

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#115]
Waste heat recovery's case study is wrong:
link: https://www.combustionandenergy.com/case-studies.php
Title:  Toyota Motor Manufacturing Corporation - Automotive Assembly Plant

**Comment by rhernandez-intertech** [comment]
Link is invalid, goes to a page not found

**Comment by koay9f** [comment]
CHANGE TO BOILER ELECTRIFICATION
Electricity should be -3900000 (or whichever direction +/- will make it so electricity goes up)
