### ISSUE TITLE
Implement Project Financing Options

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#122]
Allow user to implement project with alternative financing options. There will be effects to existing budget carryover behavior.  

After user has achieved 15%, 35%, they will get a reward of  'capital funds' to finance ONLY one project for each respective percent savings milestone. Eligible* capital-financed projects will reveal a unique button to implement.

After X years of playing the game, present new projects with new dynamic financing options to user.

*Eligible capital -financed projects - Cannot be projects which have to be renewed. What else?

Financing options:
- EEAAS
- Leasing
- Green Bond
- PACE
- VPPA

Eligible dynfin project info cards will get a table of financing options with prices. Normal implement project button will appear disabled/enabled based on the selected dynfin option beside it 

To start with each dynfin type will only have one corresponding project (slide 10)

Display differing costs/language based on financing type (slide 11)

"Things to make it harder" (slide 12) - Nice-to-haves then?

**Comment by koay9f** [comment]
Re: eligible capital-financed projects are any that do not have to be renewed. that should be the only qualifier.

Will make lists of which projects will be for each dynfin type. 
Will make more projects to fill out lists
Do we want to talk about the one project per financing type vs. maybe two financing types per project? and how that would play out?

**Comment by koay9f** [comment]
Excel sheet with breakdown of options:
[CYOS project list 2023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEE2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4411b70da2a6722ede4b24ae3aeac797b267e46/CYOS%20project%20list%202023.xlsx)

**Comment by rhernandez-intertech** [comment]
Let's meet about this issue before you get started, also create a new file for new functions and methods

**Comment by nbintertech** [comment]
Dropping effort to 0 as I'm breaking this into methods

**Comment by nbintertech** [comment]
Closing, this is no longer tracking anything
