### ISSUE TITLE
Financing - Implement free project with capital funding

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#126]
Setup logic to allow user a free project from capital funding milestones (round A, round B). For dev I have these milestones at 2% and 5%

**Comment by nbintertech** [comment]
Guessing project payment is tied to financing options with payment being annual project cost?

**Comment by koay9f** [comment]
All of this is blocked by the financing options (total project cost = sum(project payment * number of years); project payment = what gets taken out of annual/biannual budget)

**Comment by nbintertech** [comment]
This will be done #142 - I didn't see this issue when breaking down financing issues. Will try to turn it into something else financing related
