### ISSUE TITLE
Add Gameplay Mechanics and Logic README

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#147]
Add GAMEPLAY-README.MD

We can start by listing any mechanics/rules we have setup and organize them into groups/outline later.

i.e. a current rule disallows users from navigating back further than their last completed year.

may merge this into existing readme or replace some of Jordans react documentation

**Comment by koay9f** [comment]
<img width="1851" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWZTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a9783505821f21766c0f3141c49a1da0beee95a/image.png" alt="image.png" />
