### ISSUE TITLE
Update Electricity Emission factor each year

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#186]
Will get numbers soon, but for now just set it up so each year just happens to use the same number.
Year 1 ... 400
Year 2 ... 400
.
.
.
.

**Comment by koay9f** [comment]
Year = 1, EF = .371
Year = 2, EF = .358
Year = 3, EF = .324
Year = 4, EF = .311
Year = 5, EF = .305
Year = 6, EF = .302
Year = 7, EF = .300
Year = 8, EF = .291
Year = 9, EF = .285
Year = 10, EF = .276


If making something calculated based on year would be easier I can do that, but a lookup table seems easier.
for the 2 year scenario, use the second year (Year 1 & 2 = Year 2)

**Comment by koay9f** [comment]
Make sure the "initial" CO2 number that you base everything on is based on the CO2 emission factor from the end of period 1 instead of a static number
