### ISSUE TITLE
Financing Bar disappearing bug 

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/Choose-Your-Own-Adventure#191]
When playing the game with the default settings, in year 1 select Advanced Energy Monitoring with Wireless Submetering with Xaas and proceed. In Year 2 select any project with existing budget, then select Installing boiler monitors and control with Xaas, then unselect Installing boiler monitors and control and the Financing Bar disappears.  

<img width="1680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWhQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--903378b1d43e3ccd24b0294384f9f8597e9f8491/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
Fixed - When the app un-implements a project it has to unapply change to all projects, and then reapply. When it was iterating over projects to reapply it used the wrong index to find the respective financing option --> this sent NAN value input to the budget bar

**Comment by koay9f** [comment]
This was a bit hilarious to follow, but it seems to work now.
