### ISSUE TITLE
Warning dialog for Scopes

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#203]
Warning dialog for scopes, displays on year recap page and does not go backward. We also are changing to show this for only the first year

**Comment by koay9f** [comment]
Either cannot test right now due to quality of life for developers update or the warning is broken completely...

**Comment by nbintertech** [comment]
This is working for me. If you can replicate lmk. Maybe it was not first year of game?

**Comment by koay9f** [comment]
Was able to get it to show up and confirm this works.
