### ISSUE TITLE
Financing: Cost Per carbon adjustment

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#206]
We should probably adjust cost per carbon for financed projects. 

Calcs for Kristina beow. Including the formatted image and text below since platforms can't agree on text formatting standards.

### Cost per cabon (kg??) savings = total game spending / carbon savings per kg

<img width="717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0p6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf7aa7730a7a42e63cffc2e3e79fba139a6f059a/image.png" alt="image.png" />

Breakdown:
total game spending  = net costs (including hidden cost deductions and rebates) for all projects, all years
Current emissions = 
       Ng emissions = naturalGasMMBTU * naturalGasEmissionsPerMMBTU;
Elec emissions = electricityUseKWh * electricityEmissionsPerKWh;
Ng Emissions + elec Emissions;
 
Carbon savings percent = (previous emissions - current emissions) / previous emissions
carbon savings per kg = carbon savings percent * previous emissions;

**Comment by koay9f** [comment]
`carbon savings per kg = carbon savings percent * previous emissions;`
This doesn't make sense. That would just be  `(previous emissions - current emissions)`
it should be something like
`costCarbon =  totalGameSpent / (firstYearEmissions - currentYearEmissions)
total Game spending wasn't used at all in what was outlined. 
Also - the emissions probably aren't calc'd correctly b/c the PPAs don't effect the utility emissions directly.  Not sure how they are incorporated but you need to use whatever is used for the gauge.

YOU COULD use this
`costCarbon = totalGameSpent/(carbonSavePercent * firstYearEmissions)`
where carbonSavePercent is whatever is used for the gauge.

final note:
end of year calculation should include "Total still financed" that is something like
`stillFinanced = sum(annualProjectCost * (yearsFinanced - yearsPaid))`  
and then
`totalGameFinanced = totalGameSpent + stillFinanced`

forgive my naming.  making things up.  lets chat tomorrow.

**Comment by koay9f** [comment]
Looking at readme: you have the tag implementedFinancedProjects - so that should help right?  sorry if this is a duh

**Comment by nbintertech** [comment]
Need to make adjustments to game total and projected spending calcs, coming in #180
