### ISSUE TITLE
Card updates

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#21]
What all should be on cards?
Options:
% Energy savings
% Carbon savings
Cost

**Comment by rhernandez-intertech** [comment]
Cards will be updated to display the title of the project, short description, and the % energy savings.

**Comment by nbintertech** [comment]
Will implement based on mockup/changes that are also part of #25
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/eec5fd30-1654-4ed1-a879-776ed43eb97e)

**Comment by nbintertech** [comment]
![image.png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/419c1be6-15ff-49e2-94e2-4537eba37c81)
