### ISSUE TITLE
Update Game Settings

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#213]
1. We need to implement the allow budget carryover setting. The default should be no, BUT if a user has negative budget, the negative should carryover. 
2. Implement cost savings carryover - "Never", "1 Year" (current state), "Always" 
  Always - cost savings for each year, should be applied to the budget for each subsequent year

**Comment by nbintertech** [comment]
Halting on this for now, got a heads up on possible changes coming down from Kristina/Paulomi. Rachel and I need to meet on what 'always' means

**Comment by koay9f** [comment]
Always means it acts like the "renewables"  and you get the cost savings each year.
then your budget add on could just be calculated as (energyUse beginging - energyUse now) * energyCost, but then that might double count whatever you end up doing for renewables, so maybe I should just shut up...

**Comment by nbintertech** [comment]
'Always' implementation may break #275
