### ISSUE TITLE
Projects whos effects only last 1 year/period

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#22]
Doing my best to restate this for development. 

For projects that are potentially recurring and whose effects only last one year (ask for list), We need to:
- Removed/reset projects stat appliers from results in the new year
- Make project available to be selected at new year start
- If year range or interval other than 1 year, reassign the project cost as cost X interval
- Add info to project card (from Kristina)

#70 currently needs more work - dbl check status before starting

--------------
Original notes and comments below:
Projects like RECs, VPPAs, CA leak survey, steam trap survey (we'll list them) - their savings only last for as long as you keep putting money in.
Maybe a property associated with teh projects that is "needsRenewal"?  

Maybe a property associated with teh projects that is "needsRenewal"?

When two-year intervals are implemented, projects that are selected that effect only 1 year are assumed to be selected for both years of that two-year interval

Could instead do issue #70 if would be easier for the time being and tweak the "annual" projects that would not fit that mold

Note left in #70 that also applies: Note, we still need to hook up carbon savings for Wind VPPA

**Comment by rhernandez-intertech** [comment]
When two-year intervals are implemented, projects that are selected that effect only 1 year are assumed to be selected for both years of that two-year interval

**Comment by koay9f** [comment]
Could instead do issue #70 if would be easier for the time being and tweak the "annual" projects that would not fit that mold

**Comment by koay9f** [comment]
Note left in #70 that also applies: Note, we still need to hook up carbon savings for Wind VPPA

**Comment by nbintertech** [comment]
Needs #81 to work properly
