### ISSUE TITLE
Add New Projects 

### ISSUE THREAD

**Issue by rhernandez-intertech** [ORNL-AMO/Choose-Your-Own-Adventure#224]

**Comment by koay9f** [comment]
Landfill gas for boiler - the negative sign for landfill gas & natural gas are reversed. NG reduction should be positive, LFG should be negative
<img width="950" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75b816ea36987020475cf9f3219bcd0b205abf45/image.png" alt="image.png" />

**Comment by koay9f** [comment]
Total cost should be $4,000,000
<img width="957" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ef5bc14d9778aed450eebe906a3341279ef8400/image.png" alt="image.png" />

**Comment by koay9f** [comment]
Small things:
Community Wind project - Total cost should be 4,000,000 (not 660,000)
Utility-PPPA Wind project - unnecessary line breaks in text

**Comment by nbintertech** [comment]
The text line breaks are generated by the responsive styling (play with the window size to see). If we wanted to try and style it so line breaks would happen specifically we could, but not worth the effort IMO
