### ISSUE TITLE
Modeling manpower issues

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#23]
Have a project per period cap?

**Comment by koay9f** [comment]
3 per scope for now

**Comment by nbintertech** [comment]
We'll show the bottom toast bar with a red warning if they try to select more than 3

**Comment by koay9f** [comment]
if doing 2 years at a time this would be 6

**Comment by nbintertech** [comment]
We decided to limit by total projects in period. Could be easily done per scope in the future

**Comment by koay9f** [comment]
Check text in message.  2 year-intervals still says 10 projects (instead of 6?) I didn't notice what 1 year said.
