### ISSUE TITLE
Forklift update

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#230]
Text: Currently, your facility uses lead acid batteries to power your mobile forklifts, which yields high maintenance costs and low battery life for each forklift.You can replace these batteries with lithium-ion batteries, which will result in higher efficiency batteries and charging, lower maintenance costs, longer battery life, and you will also be able to shutdown a costly ventilation system. By quantifying the additional benefits of the new system, you were able to convince management to transfer some maintenance budget over for this project, reducing your required payment.
Short Text: Switch forklifts to lithium-ion batteries
Scope: Scope 2
Column: Energy Efficiency
Financing: EaaS
Electricity Reduction: 280,000 kWh
Total Project Cost: $150,000
Annual Project Cost: $37,500

**Comment by koay9f** [comment]
Needs a few fixes
* there is a line break after "life," that is unnecessary
* Electricity reduction is negative, should be positive
* Electricity % savings = 1.0%

**Comment by nbintertech** [comment]
The text line breaks are generated by the responsive styling (play with the window size to see). If we wanted to try and style it so line breaks would happen specifically we could, but not worth the effort IMO

**Comment by koay9f** [comment]
Weird.  Agreed. not worth the trouble.
Don't think this is in yet, but did just notice I can't chose to do forklifts as a capital project.

**Comment by nbintertech** [comment]
Fixed now. Capital funds eligibility was never added.
