### ISSUE TITLE
Update Github workflow

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#245]
We need to update the build job to handle new package.json commands differentiating between dev/prod. Can use branch `issue-240` . See PR -> https://github.com/ORNL-AMO/Choose-Your-Own-Adventure/pull/244

**Comment by esserhr** [comment]
Updated `web.yml` in branch `issue-240` that adds conditional to use either `build:development` or `build:production` to build based on the branch which is triggering the pipeline to execute.
