### ISSUE TITLE
Clarifying the Bundled RECs projects

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#248]
Mid-sized Solar PPPA should be a PPA, not EaaS. Just has an annual cost, not a Total project cost
Check capital project potential

I think just one problem, but putting full list of how it should act just in case (like the readme :D)

Small Carport Solar - I think is good
Payment options: Pay with Budget or EaaS - looks good
Potentially capital project: yes
Numbers: looks good
Applied payment - like "regular projects" (one time if Budget, X years if Eaas) - I think is good
Applied energy credit - "renewable" - should be getting $$ every year (there is an issue for this)

Mid-sized Solar PPPA
Payment options: Should be PPA (currently is EaaS)
Potentially capital project: no
Numbers: should not have a "total" showing (b/c PPA)
Applied payment -payment every year (not checked)
Applied energy credit - not applicable - it is GHG savings, which should be applied like all GHG savings

Rooftop mid-sized solar w storage
Payment options: Budget or loan (is good)
Potentially capital project: no
Applied payment - like "regular projects" (one time if Budget, X years if Loan) - I think is good
Applied energy credit - "renewable" - should be getting $$ every year (there is an issue for this)

Utility-PPPA Wind
Payment options: PPA (is good)
Potentially capital project: no
Numbers: is good
Applied payment -payment every year (not checked)
Applied energy credit - not applicable - it is GHG savings, which should be applied like all GHG savings

Community Wind
Payment option: Green bond only (is good)
Potentially capital project: no
Applied payment - like "regular projects" ( X years if GB) - I think is good
Applied energy credit - "renewable" - should be getting $$ every year (there is an issue for this)

**Comment by nbintertech** [comment]
Addtl changes:

Community Wind project - Total cost should be 4,000,000 (not 660,000)
Utility-PPPA Wind project - unnecessary line breaks in text
