### ISSUE TITLE
Rebates/Roadblocks should occur AFTER click proceed

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#26]
1. Surprise pop ups should appear after user has clicked proceed. They currently display when the user selects a project. 
2. This should be modified so that a single popup modal is shown and if there are multiple surprises they can next/continue through them. The congrats or roadblock should say the project it belongs to

**Comment by nbintertech** [comment]
We are scrapping the above.

Rebates/Roadblocks should be shown to the user at the year end recap page. Roablocks are already implemented as shown below
![image (3).png](https://images.zenhubusercontent.com/5e4547eef6a311c23c81ce81/08785114-781f-43ac-9209-4577db7072fc)w

**Comment by nbintertech** [comment]
- Showing consolidated utility rebates at EOY recap
- Removed surprise dialogs
- 'hiddenSurprises' (used to be the roadblock/bad surprises) are now just recapSurprises. In the future can use this array to store individualized surpises good or bad that don't fit utility rebates
- Remove some unecessary comments, other small fixes

**Comment by koay9f** [comment]
Not getting the congratulations for first "Energy Efficiency - Lighting Upgrade"
