### ISSUE TITLE
Scope 1 Fuel switching carryover

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#275]
Cost savings for fuel switching projects should never get carryover

related #213

**Comment by nbintertech** [comment]
I also added a named cost savings multiplier for regular projects (0.5) and for renewables (1). these properties can be found by searching 'initialTrackedStats' in the project.

**Comment by koay9f** [comment]
If do any project by itself, it seems to work.,

Blended Fuel for boiler & Landfill Gas for Oven, when completed together, are adding a small amount of money to the next year.  
TEST: Godless, 1year.  Budget = $700000. Select those two. $ = 0.  Next year budget should be $75k is instead 97,500
If do either by self, it is okay. 
If do electric boiler & Blended Fuel for boiler  then budget is $2500.  (should be $75k)


SIDE NOTE: Solar thermal - you should get your money back (I *THINK* this can be treated as a renewable project)
