### ISSUE TITLE
Two more projects

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#286]
Let me know if I'm forgetting anything

This project needs to act the same as the electric boiler & land fill gas projects for cost savings
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUw4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db464a8e6896933cecd8ea80c2a1cd00aa1867f1/image.png" alt="image.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUQ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d84feaa7691a135d22fb44e4544f8baebd601b3/image.png" alt="image.png" />

**Comment by nbintertech** [comment]
@rhernandez-intertech see new costSavings shouldCarryover property from #275 if needed for this. LMK if you have questions
