### ISSUE TITLE
hopefully small verbiage change

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#305]
change "Year" to "Budget Period"

<img width="1201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--655d5ced4df3c104af6feaa52445aefbba58249b/image.png" alt="image.png" />

**Comment by rhernandez-intertech** [comment]
made changes in a few other places as well, let me know if I missed anything
