### ISSUE TITLE
Vertical page jumping

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#41]
The state.lastScrollY property functionality isn't working right, causing the page to jump after clicking "back" from within a project info dialog. May also be related to page jumping when hovering over dashboard proceed button

**Comment by nbintertech** [comment]
Can't find any leads here. Still seems related to info dialog pop ups which are being removed in a current PR. Holding off.

**Comment by koay9f** [comment]
omg pls pls figure this out. it is making it really difficult to use
