### ISSUE TITLE
Quick Fixes from Review

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#60]
#s with gauges - only 1 decimal for carbon and none for NG or electricity
`Emissions from electricity` (not `Emissions from electrical grid`)
Emissions from ... #s - 1 decimal
Finances table - hover - no decimals (there are some in available)

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/78ec6ba1-e157-4c95-8666-47a4b95d9d90)

Make sure numbers are formatted as ###,###,###
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1d6c858f-f98f-4c71-9b15-aa99acb31b4f)

--------

If this would be quick, otherwise, "Nice to Have" and pls make a new issue
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ffa11044-18d1-4d16-afd3-aafff5f65c73)

**Comment by koay9f** [comment]
Have total money spent on end of year recap
Have total money spent / % C savings in end of year recap

**Comment by nbintertech** [comment]
Removed comment work and last todo from desc to issue 72
