### ISSUE TITLE
App-wide Accessibility Styling

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#67]
Rachel and I will brainstorm and divvy up

1. We need to bump up the accessibility for higher priority titles, headers, and paragraph text. in all pages
- Remove the italics
- Less muted text
- bump up font-weights
2. Let's demo/screen shot the app in 100% width vs current centered width and see what people like
- What if we expanded the container width, but lowered card width to show more cards on the screen at once? Could play with this.
- What if we lower current width of year recap to reduce whitespace and center focus.

**Comment by rhernandez-intertech** [comment]
When info is selected for a project, blur and/or more darken background.
And on project info page and compare page, make textbox boarders thicker
