### ISSUE TITLE
Additional Utility / EOY stats

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#72]
Pulled from issue 60
- Have total money spent on end of year recap
- Have total money spent / % C savings in end of year recap
- Add the two sections shown below
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ffa11044-18d1-4d16-afd3-aafff5f65c73)

**Comment by koay9f** [comment]
EOY recap:
* would be useful to know **total** money spent, and not just this year ("This year you spent $265,000, including hidden costs. You have spent $501,000 total")
* $/kgC should have 2 decimal points and be for all time, not just this year (not sure what it is at the moment - need decimals and to finish math checker)
