### ISSUE TITLE
Yearly Recap - top area fixes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#85]
1 - $/kg carbon
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/e9aa3525-0465-4341-b469-ac0843df54d8)
2 - Have a % carbon total somewhere.  Maybe maintain the gauges from main screen?  but something to actually show current progress

**Comment by nbintertech** [comment]
cost per kg reduced decimals fix is in 81
