### ISSUE TITLE
Weird solar carport renewal project

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/Choose-Your-Own-Adventure#88]
So, users would select solarPanelsCarPort. Stats and money would be applied for that year.
The next year, the stats are gone, the project is not chooseable again and instead they should choose solarPanelsCarPortMaintenance.  That acts like a regular renew project

Current code for two projects: 

```Projects[Pages.solarPanelsCarPort] = new ProjectControl({
    pageId: Pages.solarPanelsCarPort,
    cost: 150_000,
    statsInfoAppliers: {
        electricityUseKWh: absolute(-537_000),
    },
    statsActualAppliers: {
        electricityUseKWh: absolute(-537_000),
    },
    statsRecapAppliers: {
        financesAvailable: absolute(-30_000),
        moneySpent: absolute(30_000),
    },
    recapSurprises: [{
        title: 'Uh oh - Bad Asphalt!',
        text: 'While assessing the land in person, the contractor found that the parking lot\'s {asphalt needs replacement}. This will require an {additional $30,000} for the carport’s installation.',
        avatar: {
            icon: <TrafficConeIcon />,
            backgroundColor: 'rgba(54,31,6,0.6)',
            color: 'rgb(255 135 33)',
        }
    }],
    title: 'Small Carport Solar Installation',
    shortTitle: 'Install solar panels on new facility carport',
    choiceInfoText: [
        'You decided to look into installing a small covered carport with a solar electricity generation system.',
	    'Given the sizing of your parking lot and available room, you decide on a {0.25 MW system} and using parking in the carport as an incentive to well performing or energy saving employees.  You decide to pay for the carport outright and not via a power purchase agreement.,'
	    'You will recieve {CREDITs} to your budget for the energy generated (and not purchased).'
    ],
    choiceInfoImg: 'images/solar-panels.png',
    choiceInfoImgAlt: 'Solar panels on the roof top of a car parking lot.',
    recapDescription: 'Insert flavor text here!',
    caseStudy: {
        title: 'Lockheed Martin 2.25 Megawatts Solar Carport',
        url: 'https://www.agt.com/portfolio-type/lockheed-martin-solar-carport/',
        text: 'In 2017, {Lockheed Martin} installed a 4-acre solar carport and was able to provide {3,595,000} kWh/year, or enough electricity to power almost {500 homes} annually.',
    },
		energySavingsPreviewButton: {
		text: '1.8%',
		variant: 'text',
		startIcon: <BoltIcon/>,
	},
});
Projects[Pages.solarPanelsCarportMaintenance] = new ProjectControl({
	pageId: Pages.solarPanelsCarportMaintenance,
	renewalRequired: true,
	cost: 10_000,
    statsInfoAppliers: {
        electricityUseKWh: absolute(-537_000),
    },
    statsActualAppliers: {
        electricityUseKWh: absolute(-537_000),
    },
	title: 'Carport Solar - Maintenance',
	shortTitle: 'Continue receiving energy from your solar generation. YOU CAN SELECT THIS ANNUALLY.',
	choiceInfoText: ['You have installed and paid for your carport solar but need to perform small maintenance tasks for it. YOU MUST SELECT THIS PROJECT EVERY YEAR to continue recieving the energy credits.'],
	choiceInfoImg: '',
	choiceInfoImgAlt: '',
	choiceInfoImgObjectFit: 'contain',
	recapDescription: 'Insert flavor text here!',
	caseStudy: undefined,
	energySavingsPreviewButton: {
		text: '1.8%',
		variant: 'text',
		startIcon: <BoltIcon/>,
	},
});
```

I needed to add this to solarPanelsCarPortMaintenance
```     visible: state => state.completedProjects.some(project => project.page === Pages.solarPanelsCarPort)
```

what I thought would work
Projects[Pages.solarPanelsCarPort] = new ProjectControl({
    pageId: Pages.solarPanelsCarPort,
    cost: 150_000,
	renewalRequired: true,
    statsInfoAppliers: {
        electricityUseKWh: absolute(-537_000),
    },
    statsActualAppliers: {
        electricityUseKWh: absolute(-537_000),
    },
    statsRecapAppliers: {
        financesAvailable: absolute(-30_000),
        moneySpent: absolute(30_000),
    },
    recapSurprises: [{
        title: 'Uh oh - Bad Asphalt!',
        text: 'While assessing the land in person, the contractor found that the parking lot\'s {asphalt needs replacement}. This will require an {additional $30,000} for the carport’s installation.',
        avatar: {
            icon: <TrafficConeIcon />,
            backgroundColor: 'rgba(54,31,6,0.6)',
            color: 'rgb(255 135 33)',
        }
    }],
    title: 'Small Carport Solar Installation',
    shortTitle: 'Install solar panels on new facility carport',
    choiceInfoText: [
        'You decided to look into installing a small covered carport with a solar electricity generation system.',
	    'Given the sizing of your parking lot and available room, you decide on a {0.25 MW system} and using parking in the carport as an incentive to well performing or energy saving employees.  You decide to pay for the carport outright and not via a power purchase agreement.,'
	    'You will recieve {CREDITs} to your budget for the energy generated (and not purchased).'
    ],
    choiceInfoImg: 'images/solar-panels.png',
    choiceInfoImgAlt: 'Solar panels on the roof top of a car parking lot.',
    recapDescription: 'Insert flavor text here!',
    caseStudy: {
        title: 'Lockheed Martin 2.25 Megawatts Solar Carport',
        url: 'https://www.agt.com/portfolio-type/lockheed-martin-solar-carport/',
        text: 'In 2017, {Lockheed Martin} installed a 4-acre solar carport and was able to provide {3,595,000} kWh/year, or enough electricity to power almost {500 homes} annually.',
    },
		energySavingsPreviewButton: {
		text: '1.8%',
		variant: 'text',
		startIcon: <BoltIcon/>,
	},

    disabled: state => state.completedProjects.some(project => project.page === Pages.solarPanelsCarPort)

});
Projects[Pages.solarPanelsCarportMaintenance] = new ProjectControl({
	pageId: Pages.solarPanelsCarportMaintenance,
	renewalRequired: true,
	cost: 10_000,
    statsInfoAppliers: {
        electricityUseKWh: absolute(-537_000),
    },
    statsActualAppliers: {
        electricityUseKWh: absolute(-537_000),
    },
	title: 'Carport Solar - Maintenance',
	shortTitle: 'Continue receiving energy from your solar generation. YOU CAN SELECT THIS ANNUALLY.',
	choiceInfoText: ['You have installed and paid for your carport solar but need to perform small maintenance tasks for it. YOU MUST SELECT THIS PROJECT EVERY YEAR to continue recieving the energy credits.'],
	choiceInfoImg: '',
	choiceInfoImgAlt: '',
	choiceInfoImgObjectFit: 'contain',
	recapDescription: 'Insert flavor text here!',
	caseStudy: undefined,
	energySavingsPreviewButton: {
		text: '1.8%',
		variant: 'text',
		startIcon: <BoltIcon/>,
	},
    visible: state => state.completedProjects.some(project => project.page === Pages.solarPanelsCarPort)

});

**Comment by nbintertech** [comment]
- Added ability to have projects with single time period implementation savings (solar carport), that then reveal maintenance or dependant projects
- Moved large wind pppa to bundled recs

**Comment by koay9f** [comment]
The Carport solar is NOT getting x2 to the electricity savings when in 2 years.
It looks like the other renewables and carport maintenance are behaving,  but will keep checking
Things that are correctly working
it goes away the next period
the % savings goes away the next period
will let you know if I found anything else

**Comment by koay9f** [comment]
The Carport solar is NOT getting x2 to the electricity savings when in 2 years.
It looks like the other renewables and carport maintenance are behaving,  but will keep checking
Things that are correctly working
it goes away the next period
the % savings goes away the next period
will let you know if I found anything else
