### ISSUE TITLE
Fix project budget/manpower limits, costs in 2 year, cost per carbon

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/Choose-Your-Own-Adventure#96]
Make sure project budget limits and manpower limits warning messages show with all projects now that renewable projects are included.

Make sure non-renewable projects are charged cost for 1 year in 2 year game settings

**Comment by koay9f** [comment]
Budget warning is not working
I think manpower is okay
I think the second is okay? I haven't noticed it being a problem.
